name: ci
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy-image:
    runs-on: ubuntu-latest
    steps:
      # 拉取master分支
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64, linux/arm64,  linux/arm/v7
